blank_issues_enabled: false
contact_links:
  - name: Discord
    url:  https://discord.gg/GuDyREsNkj
    about: Join our Discord server. Feel free to ask for any question about Athena OS, IT or Cyber Security.
